name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: cypress/reports/

      - name: Send Email on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "❌ Cypress Tests FAILED - ${{ github.repository }}"
          to: deepthikarnam12@gmail.com
          from: Cypress Bot <${{ secrets.MAIL_USERNAME }}>
          body: |
            Hi Achyutha,

            Cypress tests FAILED on repo ${{ github.repository }}.

            Commit: ${{ github.event.head_commit.message }}
            Branch: ${{ github.ref }}
            See run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            HTML Report is in Artifacts.

            - Cypress Bot